In [17]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import os
import time
np.set_printoptions(suppress = True)
import sobol
from Minimization import minimization
from concurrent.futures import ProcessPoolExecutor
import multiprocessing
obs_series = pd.read_csv('data.csv', delimiter=',')
obs_series = np.array(obs_series.iloc[:,1:]).T

In [40]:
np.random.seed(1)
obs_series = pd.read_csv('data.csv', delimiter=',')
obs_series = np.array(obs_series.iloc[:,1:]).T


n_points = 56
sobol_sequence = sobol.sample(dimension=22, n_points=n_points)
sobol_sequence[:,1:] = sobol_sequence[:,1:]*2 -1
start = np.array_split(sobol_sequence, n_points)
start_time = time.time()
results = []
for i in range(n_points):
    results.append(minimization(start[i]))

run_time = time.time() - start_time
print(run_time)
results

/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18

397.8199770450592


[['Singular',
  [],
  [],
  array([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ])],
 ['Unstable',
  [],
  [],
  array([ 0.75, -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.25,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.375, -0.25 ,  0.25 , -0.75 ,  0.75 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0.75 , -0.25 ,  0.25 , -0.75 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 , -0.25 ,  0.75 ,  0.75 ,  0.25 ])],
 ['Unstable',
  [],
  [],
  array([ 0.875,  0.75 , -0.75 ,  0.25 , -0.25 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 ,  0.75 , -0.75 ,  0.25 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0

In [41]:
np.random.seed(1)
obs_series = pd.read_csv('data.csv', delimiter=',')
obs_series = np.array(obs_series.iloc[:,1:]).T

n_points = 56
sobol_sequence = sobol.sample(dimension=22, n_points=n_points)
sobol_sequence[:,1:] = sobol_sequence[:,1:]*2 -1
start = np.array_split(sobol_sequence, n_points)

start_time = time.time()
if __name__ == '__main__':
    pool = multiprocessing.Pool()
    results = pool.map(minimization, start)

run_time = time.time() - start_time
print(run_time)
results

/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18

351.2902867794037


[['Singular',
  [],
  [],
  array([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ])],
 ['Unstable',
  [],
  [],
  array([ 0.75, -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.25,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.375, -0.25 ,  0.25 , -0.75 ,  0.75 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0.75 , -0.25 ,  0.25 , -0.75 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 , -0.25 ,  0.75 ,  0.75 ,  0.25 ])],
 ['Unstable',
  [],
  [],
  array([ 0.875,  0.75 , -0.75 ,  0.25 , -0.25 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 ,  0.75 , -0.75 ,  0.25 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0

In [42]:
obs_series = pd.read_csv('data.csv', delimiter=',')
obs_series = np.array(obs_series.iloc[:,1:]).T
np.random.seed(1)
n_points = 56
sobol_sequence = sobol.sample(dimension=22, n_points=n_points)
sobol_sequence[:,1:] = sobol_sequence[:,1:]*2 -1
start = np.array_split(sobol_sequence, n_points)

start_time = time.time()
if __name__ == '__main__':
    with ProcessPoolExecutor() as pool:
        results = pool.map(minimization, start)
    results = [r for r in results]

run_time = time.time() - start_time
print(run_time)
results

/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18

352.8149778842926


[['Singular',
  [],
  [],
  array([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ])],
 ['Unstable',
  [],
  [],
  array([ 0.75, -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.25,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.375, -0.25 ,  0.25 , -0.75 ,  0.75 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0.75 , -0.25 ,  0.25 , -0.75 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 , -0.25 ,  0.75 ,  0.75 ,  0.25 ])],
 ['Unstable',
  [],
  [],
  array([ 0.875,  0.75 , -0.75 ,  0.25 , -0.25 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 ,  0.75 , -0.75 ,  0.25 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0

In [8]:
n_points = 1000
sobol_sequence = sobol.sample(dimension=22, n_points=n_points)
sobol_sequence[:,1:] = sobol_sequence[:,1:]*2 -1
start = np.array_split(sobol_sequence, n_points)

In [10]:
%%time
if __name__ == '__main__':
    with ProcessPoolExecutor() as pool:
        results = pool.map(minimization, start)
    results = [r for r in results]

with open('data_'+str(batch_n)+'.pkl', 'wb') as f:
       pickle.dump(results, f)

/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:80: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))
/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18

CPU times: user 45.2 ms, sys: 105 ms, total: 150 ms
Wall time: 14.5 s


[['Singular',
  [],
  [],
  array([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ])],
 ['Unstable',
  [],
  [],
  array([ 0.75, -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.25,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.375, -0.25 ,  0.25 , -0.75 ,  0.75 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0.75 , -0.25 ,  0.25 , -0.75 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 , -0.25 ,  0.75 ,  0.75 ,  0.25 ])],
 ['Unstable',
  [],
  [],
  array([ 0.875,  0.75 , -0.75 ,  0.25 , -0.25 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 ,  0.75 , -0.75 ,  0.25 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0

In [6]:
results

[['Singular',
  [],
  [],
  array([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ])],
 ['Unstable',
  [],
  [],
  array([ 0.75, -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 , -0.5 ,
          0.5 , -0.5 ,  0.5 , -0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.25,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 ,  0.5 , -0.5 , -0.5 ,  0.5 ,
         -0.5 ,  0.5 , -0.5 ,  0.5 ])],
 ['Unstable',
  [],
  [],
  array([ 0.375, -0.25 ,  0.25 , -0.75 ,  0.75 ,  0.75 , -0.75 ,  0.25 ,
         -0.75 ,  0.75 , -0.25 ,  0.25 , -0.75 , -0.25 ,  0.25 , -0.75 ,
          0.25 , -0.25 , -0.25 ,  0.75 ,  0.75 ,  0.25 ])]]

In [ ]:
stable = False
n_trials = 0
while stable == False:
    start = np.concatenate((np.random.uniform(0,1,1), np.random.uniform(-1,1,21)))
    try:
        μ0, Σ0, Ass, Σs = init_kf(start)
        n_trials +=1
        if (np.all(np.linalg.eigvals(Σ0)>=0)) & (np.all(abs(np.linalg.eigvals(Ass))<1) & (np.all(np.linalg.eigvals(Σs)>=0))):
            stable = True
        else:
            stable = False
    except: 
        n_trials +=1
        stable = False  

In [2]:
minimization([100,:])

/Users/haominqin/Dropbox/Mac/Documents/Estimation Projects/18th Version, sobol seq MLE b21=0/Minimization.py:78: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))


[      fun: nan
  hess_inv: <22x22 LbfgsInvHessProduct with dtype=float64>
       jac: array([ 70.53113222, -28.30302054, -14.0999874 ,  14.1204965 ,
          6.57942114,  18.14837571,  37.34630832,  -8.94760893,
         31.90193658,  -3.11729311, -52.24906122,  30.80404004,
         16.9519809 ,  -3.29764591, -28.41225086,  19.08570096,
         -1.59657248,   1.27351996,  50.46094915,   0.78257472,
         -3.97340048,  49.4986128 ])
   message: 'ABNORMAL_TERMINATION_IN_LNSRCH'
      nfev: 207
       nit: 2
      njev: 9
    status: 2
   success: False
         x: array([ 0.        , -4.95904567, -4.96776555,  4.97496445,  4.99891985,
         4.9849263 ,  4.97167446,  5.        ,  4.95403253,  4.97827912,
         5.        ,  4.96159238, -5.        , -5.        , -4.94416821,
        -5.        , -4.99742361, -5.        ,  4.95490621,  4.99377102,
        -4.98160789,  4.95177968]),
 [array([ 0., -5., -5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5., -5.,
         -5., -5., -5.,

In [78]:
def init_kf(θ):
    
    λ, η, b11, b22, As11, As12, As13, As14, As21, As22, As23, As24, As31, As32, As33, As34, Bs11, Bs21, Bs22, Bs31, Bs32, Bs33 = θ
    ones = np.ones([3,1])
    
    Ass = np.array([[As11, As12, As13],\
                    [As21, As22, As23],\
                    [As31, As32, As33]])
    Aso = np.array([[As14],\
                    [As24],\
                    [As34]])
    Bs =  np.array([[Bs11, 0,    0],\
                    [Bs21, Bs22, 0],\
                    [Bs31, Bs32, Bs33]])
    
    μs = sp.linalg.solve(np.eye(3) - Ass, Aso) 
    Σs = sp.linalg.solve_discrete_lyapunov(Ass, Bs@Bs.T)
    
    β = sp.linalg.solve(np.hstack([Σs@np.array([[1,1],[0,-1],[-1,0]]), ones]).T, np.array([[0,0,1]]).T)                                     
    γ1 = np.array([[1],[0],[0]]) - sp.linalg.inv(Σs)@ones/(ones.T@sp.linalg.inv(Σs)@ones)
    γ2 = np.array([[0],[1],[0]]) - sp.linalg.inv(Σs)@ones/(ones.T@sp.linalg.inv(Σs)@ones)
    γ3 = np.array([[0],[0],[1]]) - sp.linalg.inv(Σs)@ones/(ones.T@sp.linalg.inv(Σs)@ones)
    Γ = np.hstack([γ1, γ2, γ3])
    
    Z01 = β.T@(obs_series[:,[0]] - μs)
    Σz01 = 0
    Z02 = η/(1-λ)
    Σz02 = b22**2/(1-λ**2)
    S0 = Γ.T@(obs_series[:,[0]] - μs) + μs
    Σs0 = (1/(ones.T@np.linalg.inv(Σs)@ones))[0][0]
    
    μ0 = np.array([[Z01[0][0]],\
                   [Z02],\
                   [S0[0][0]],\
                   [S0[1][0]],\
                   [S0[2][0]],\
                   [1]])
    Σ0 = np.array([[Σz01,0,    0,   0,   0,   0],\
                   [0,   Σz02, 0,   0,   0,   0],\
                   [0,   0,    Σs0, Σs0, Σs0, 0],\
                   [0,   0,    Σs0, Σs0, Σs0, 0],\
                   [0,   0,    Σs0, Σs0, Σs0, 0],\
                   [0,   0,    0,   0,   0,   0]])    
    return μ0, Σ0, Ass, Σs

In [10]:
start

array([0.9140625, 0.7578125, 0.8046875, 0.9765625, 0.8828125, 0.1015625,
       0.5078125, 0.2421875, 0.0390625, 0.1953125, 0.4765625, 0.5859375,
       0.3984375, 0.6015625, 0.7421875, 0.6953125, 0.3046875, 0.0859375,
       0.7421875, 0.9453125, 0.1640625, 0.0546875])

In [9]:
start = sobol.sample(dimension=22, n_points=1000)[100,:]

In [3]:
%%time
np.random.seed((os.getpid() * int(time.time())) % 123456789)
stable = False
n_trials = 0
while stable == False:
    start = np.concatenate((np.random.uniform(0,1,1), np.random.uniform(-5,5,21)))
    try:
        μ0, Σ0, Ass, Σs = init_kf(start)
        n_trials +=1
        if (np.all(np.linalg.eigvals(Σ0)>=0)) & (np.all(abs(np.linalg.eigvals(Ass))<1) & (np.all(np.linalg.eigvals(Σs)>=0))):
            stable = True
        else:
            stable = False
    except: 
        n_trials +=1
        stable = False  

CPU times: user 2.07 s, sys: 5.2 ms, total: 2.07 s
Wall time: 2.07 s


In [4]:
def Kalman_Filter(obs, D, F, A, B, μ0, Σ0):

    state_μ = np.zeros([A.shape[1], obs.shape[1]])
    state_μ[:,[0]] = μ0
    state_Σ = np.zeros([A.shape[1], A.shape[1], obs.shape[1]])
    state_Σ[:,:,0] = Σ0

    ll = 0

    for t in range(obs.shape[1]-1):
        μt = state_μ[:,[t]]
        Σt = state_Σ[:,:,t]
        KΣt = (A@Σt@D.T + B@F.T)@np.linalg.inv(D@Σt@D.T+F@F.T)
        state_μ[:,[t+1]] = A@μt + KΣt@(obs[:,[t+1]] - D@μt)
        state_Σ[:,:,t+1] = A@Σt@A.T + B@B.T - (A@Σt@D.T + B@F.T)@np.linalg.inv(D@Σt@D.T + F@F.T)@(D@Σt@A.T+F@B.T)

        Ω = D@Σt@D.T + F@F.T
        ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))

    return state_μ, state_Σ ,ll

In [5]:
def ll(θ):

    λ, η, b11, b22, As11, As12, As13, As14, As21, As22, As23, As24, As31, As32, As33, As34, Bs11, Bs21, Bs22, Bs31, Bs32, Bs33 = θ

    A = np.array([[1,   1,   0,     0,     0,     0],\
                  [0,   λ,   0,     0,     0,     η],\
                  [0,   0,   As11,  As12,  As13,  As14],\
                  [0,   0,   As21,  As22,  As23,  As24],\
                  [0,   0,   As31,  As32,  As33,  As34],\
                  [0,   0,   0,     0,     0,     1]])
    B = np.array([[b11, 0,   0,     0,     0],\
                  [0,   b22, 0,     0,     0],\
                  [0,   0,   Bs11,  0,     0],\
                  [0,   0,   Bs21,  Bs22,  0],\
                  [0,   0,   Bs31,  Bs32,  Bs33],\
                  [0,   0,   0,       0,   0]])
    D = np.array([[1,   1,   As11,  As12,  As13,  As14],\
                  [1,   1,   As21,  As22,  As23,  As24],\
                  [1,   1,   As31,  As32,  As33,  As34]])
    F = np.array([[b11, 0,   Bs11,  0,     0],\
                  [b11, 0,   Bs21,  Bs22,  0],\
                  [b11, 0,   Bs31,  Bs32,  Bs33]])

           
    μ0, Σ0, _, _ = init_kf(θ)
    
    _, _, ll = Kalman_Filter(obs_series, D, F, A, B, μ0, Σ0)

    return -ll[0][0]

    
def callback(x):
    fobj = ll(x)
    θseries.append(x)
    llseries.append(fobj)

In [10]:
# start = np.array([0.9048, 0.0004, 0.0034, -0.0012, 0.5229, 0.0343, 0.0018, 0.0530, -2.5682, 1.1660, 0.0044, 0.2483, -4.1665, 0.3062, 1.0088, 0.4542, 0.0010, 0.0327, 0.0040, 0.0060, -0.0382, 0.0019])

In [9]:
# ll(start)

In [7]:
stable = False
n_trials = 0
while stable == False:
    start = np.concatenate((np.random.uniform(0,1,1), np.random.uniform(-5,5,21)))
    try:
        μ0, Σ0, Ass, Σs = init_kf(start)
        n_trials +=1
        if (np.all(np.linalg.eigvals(Σ0)>=0)) & (np.all(abs(np.linalg.eigvals(Ass))<1) & (np.all(np.linalg.eigvals(Σs)>=0))):
            stable = True
        else:
            stable = False
    except: 
        n_trials +=1
        stable = False  
        
bnds = ((0,1),(-5,5),\
        (-5,5),(-5,5),\
        (-5,5),(-5,5),(-5,5),(-5,5),\
        (-5,5),(-5,5),(-5,5),(-5,5),\
        (-5,5),(-5,5),(-5,5),(-5,5),\
        (-5,5),(-5,5),(-5,5),(-5,5),(-5,5),(-5,5))
θseries = []
llseries = []

θ_opt = sp.optimize.minimize(ll, start, method = 'L-BFGS-B', bounds = bnds, callback = callback, tol=1e-6)  

/var/folders/5t/8szxl21n72g75qlj1hj_gqyw0000gr/T/ipykernel_80280/2757302421.py:18: RuntimeWarning: invalid value encountered in log
  ll += (-0.5*obs_series.shape[0]*np.log(2*np.pi) - 0.5*np.log(np.linalg.det(Ω)) - 0.5*(obs[:,[t+1]] - D@μt).T@np.linalg.inv(Ω)@(obs[:,[t+1]] - D@μt))


In [8]:
θ_opt

      fun: nan
 hess_inv: <22x22 LbfgsInvHessProduct with dtype=float64>
      jac: array([  73.77739166,   28.14608723,   13.02860263,   13.02855716,
       -123.72347631, -165.41676005, -236.08681802,   39.04779102,
        -78.8665607 , -115.39118602, -186.96077973,   38.80659302,
        -38.40327759,  -65.99379998,  -99.96133546,   19.76504803,
         22.24419418,   12.20701059,   -8.77926146,    7.05986172,
         20.9514384 ,  -49.10557466])
  message: 'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 115
      nit: 1
     njev: 5
   status: 2
  success: False
        x: array([ 0.,  5.,  5.,  5., -5., -5.,  5., -5.,  5.,  5., -5.,  5.,  5.,
        5., -5.,  5.,  5., -5., -5., -5., -5., -5.])

In [3]:
datadir = os.getcwd()
onlyfiles = [f for f in os.listdir(datadir) if (os.path.isfile(os.path.join(datadir, f)))&(f[-3:]=='pkl')]

In [4]:
file = []
for i in onlyfiles:
    with open(i, 'rb') as f:
        temp = pickle.load(f)
        file = file + temp

In [6]:
file[0]

['Failure',
 [array([ 0.31161264,  2.14838734, -1.44087488,  0.75413895,  2.17325654,
          2.35640411,  3.85549901,  4.93818656,  2.34057107,  4.1569598 ,
          1.59342777,  0.44692526, -2.90334321, -1.67926886, -2.82723535,
         -1.60112861,  3.53167621,  3.17902539, -2.06646662,  0.43949391,
          3.05555824,  0.84234281])],
 [nan],
 array([ 0.64747944, -0.92517874,  2.39527245, -3.82219594, -0.87350467,
        -0.49295435,  2.62191653,  4.87156191, -0.5258528 ,  3.24830211,
        -2.07829281, -4.4605351 , -0.6434945 ,  1.89992924, -0.48535496,
         0.86187954,  1.9490664 ,  1.2163164 ,  1.09539643, -4.47597622,
         0.95977211, -3.63892294])]

In [7]:
funs = []
xs = []
θs = []
for i in file:
    try:
        if np.isnan(i[0].fun) == False:
            θs.append(i[0])
            funs.append(i[0].fun)
            xs.append(i[0].x)
    except:
        pass

In [13]:
θs

[      fun: 2881.28214314155
  hess_inv: <22x22 LbfgsInvHessProduct with dtype=float64>
       jac: array([ 669.24121746,  172.28339962,  -93.49155391, -252.43125505,
         -47.21987381,  -34.79913197,   12.96748459,  -17.07126113,
          29.55966938,   12.24443629,    5.8685146 ,   10.26301113,
         -61.31554111,  -25.22770062,   37.6197479 ,  -32.60061041,
         -11.92515818,  -34.09404619,  -47.07221734,   28.40647557,
          -3.38868633,   62.30320688])
   message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
      nfev: 115
       nit: 1
      njev: 5
    status: 0
   success: True
         x: array([ 0.2342499 ,  3.62634078,  2.60450917,  0.44149087, -3.69719804,
        -3.59968552, -3.55367634,  3.15041001,  4.46742125,  3.41153175,
         3.54225888, -3.3379954 ,  2.76521173,  3.94640665,  3.77466539,
        -3.51749797, -4.57522244,  3.21255827, -4.94014452,  4.97240951,
        -3.46318387,  3.00176184]),
       fun: 3076.1230406263107
  hess_inv: <2

In [43]:
xs[-4]

array([ 0.27803033, -4.19116431,  4.82763623,  7.69717988, -6.58093635,
       -6.58033427, -6.55531535,  5.31796613,  6.23387145,  6.73025239,
        7.14687936, -3.57440976,  6.7374449 ,  6.57842181,  6.68951388,
       -7.38618683, -4.25838013,  5.25617421,  4.93885834, -6.84438366,
       -7.38313909,  2.3122027 ])

In [45]:
xs[-9]

array([ 0.37272289,  1.82176518,  3.8030896 , -4.16016732,  5.36942034,
        7.2930775 , -5.88503971,  4.14090907, -5.95217777, -5.35781495,
        5.74406966, -6.23157698,  6.59201907,  3.76838808, -5.66875584,
        4.58306449, -7.27987981,  5.30415904,  5.91427353, -5.74185467,
       -6.19056679, -6.2327953 ])

In [42]:
funs

[4110.465221180151,
 3587.8542594670066,
 3836.452030990295,
 3461.875403130969,
 7733.459728265757,
 3697.114076851317,
 3423.2748879502483,
 7009.119838531625,
 4518.601976497295,
 3478.30789385516,
 3319.8352932638218,
 3556.65523408341,
 15358.639300460265,
 4695.174676267942,
 3639.8425262123824,
 3322.6894197631623,
 3738.469382755485,
 4247.799224426205,
 3345.8951472463787]

In [65]:
np.sort([i[0] for i in xs])

array([0.01003066, 0.01151838, 0.01696329, 0.0511458 , 0.10224803,
       0.13418638, 0.16212266, 0.16276937, 0.18413284, 0.18420003,
       0.1863224 , 0.26304503, 0.27803033, 0.32411051, 0.33228348,
       0.37272289, 0.40452049, 0.4401145 , 0.69371745])

In [59]:
np.argsort([i[0] for i in xs])

array([ 0,  8,  3,  9,  7,  5, 11, 17,  4, 18, 12,  2, 15,  1,  6, 10, 13,
       16, 14])

In [70]:
xs[11]

array([ 0.16212266, -6.45087777,  0.13012616,  4.36111523, -6.14849317,
       -6.10502725,  5.77245728, -6.17449096,  5.98112899,  6.21278622,
       -6.28691299,  6.54263537, -6.49968624, -6.46602757,  6.30370799,
       -6.49175554,  0.210793  ,  7.6836343 ,  7.09705699, -5.73450058,
       -7.11193779,  7.04037598])

In [67]:
xs[17]

array([ 0.16276937, -0.62385591,  7.54522728, -5.87819202,  7.58398139,
        7.99303427, -7.96440027,  8.37809368, -8.2798539 , -7.05091249,
        7.01357717, -7.17331358,  7.13569186,  8.37492624, -8.34832439,
        7.2744976 , -7.68852265,  7.24644146, -7.46668169,  6.85743498,
        3.60862406,  0.17033418])

In [68]:
xs[4]

array([ 0.18413284,  1.43918306, -3.86266857,  6.62517578,  7.44091588,
        6.44734014, -5.15783269,  6.72579977, -6.38807902, -5.96450524,
        6.07772931, -4.70675293,  4.67644934,  5.81340812, -7.84356837,
        7.08941338, -4.75536649,  7.17624687, -6.60476305, -6.87433576,
        7.84743596,  2.82415681])

In [69]:
xs[18]

array([ 0.18420003,  3.46891868,  7.54158826,  8.65881749,  6.79700721,
        6.26705474, -6.88670329,  6.7278329 ,  6.09531141,  6.90082874,
       -5.90814734,  6.631699  , -6.60131713, -6.89497   ,  6.57715065,
       -5.09119688, -4.89922226,  1.44417309, -7.96951001, -5.07634999,
        6.63086954, -7.93926962])